
export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';
export const USER_SIGNOUT = 'USER_SIGNOUT';

export const BASEURL ='https://reqres.in'

export const USER_DETAILS_REQUEST ='USER_DETAILS_REQUEST'
export const USER_DETAILS_SUCCESS ='USER_DETAILS_SUCCESS'
export const USER_DETAILS_FAIL ='USER_DETAILS_FAIL'

export const SINGLE_USER_DETAILS_REQUEST ='SINGLE_USER_DETAILS_REQUEST'
export const SINGLE_USER_DETAILS_SUCCESS ='SINGLE_USER_DETAILS_SUCCESS'
export const SINGLE_USER_DETAILS_FAIL ='SINGLE_USER_DETAILS_FAIL'